#!/usr/bin/env ansible-playbook
---

- name: 'OSX specific setup'
  hosts: localhost
  become: no
  roles:
    - homebrew

- name: 'ArchLinux specific setup'
  hosts: localhost
  roles:
    - { role: archlinux, become: yes }
    - i3

- name: 'Development machine dotfile setup'
  hosts: localhost
  become: no
  roles:
    - dotfiles

...
