#!/usr/bin/env ansible-playbook
---

- name: 'Development machine dotfile setup'
  hosts: all
  become: no
  roles:
    - dotfiles

- name: 'OSX specific setup'
  hosts: osx
  become: no
  roles:
    - homebrew

- name: 'ArchLinux specific setup'
  hosts: archlinux
  become: yes
  roles:
    - archlinux
    - i3

...
