---

- name: 'Install base applications.'
  pacman:
    name: "{{ base_applications }}"
    state: present
  become: yes
  when: ansible_facts['os_family'] == 'Archlinux'

- name: 'Install dvm.'
  shell: 'curl -sL https://howtowhale.github.io/dvm/downloads/latest/install.sh | sh'
  when: ansible_facts['os_family'] == 'Archlinux'

...
